# - name: Apply mysql.cnf
#   file:
#     src: "/home/{{ application_user }}/git/isucon/mysql/{{ item }}"
#     dest: "/etc/mysql/{{ item }}"
#     owner: root
#     group: root
#     state: hard
#     force: yes
#   with_items:
#     - mysql.cnf
#     - conf.d/mysql.cnf
#     - mysql.conf.d/mysql.cnf
#     - mysql.conf.d/mysqld.cnf


- name: slow.logを作成しておく
  file:
    path: /var/log/mysql/slow.log
    owner: mysql
    group: mysql
    state: touch

- name: Reload mysql
  systemd:
    name: mysql
    state: restarted
    daemon_reload: yes
    enabled: yes
