- name: Pull remote repository
  become: yes
  become_user: "{{ application_user }}"
  git:
    repo: "{{ repository }}"
    dest: "/home/{{ application_user }}/git"
    ssh_opts: "-i {{ deploy_key }}"
    accept_hostkey: yes
    force: yes
