file: /var/log/nginx/access.log
sort: sum
reverse: true
format: md
output: count,1xx,2xx,3xx,4xx,5xx,method,uri,sum,avg,p99,sum_body,avg_body
matching_groups:
  - '^.*.js$'
  - '^.*.css$'
  - '^.*.png$'
  - '^/api/condition/[0-9a-z-]+$'
  - '^/api/isu/[0-9a-z-]+$'
  - '^/isu/[0-9a-z-]'
  - '^/isu/[0-9a-z-]/condition'
  - '^/isu/[0-9a-z-]/graph'

ltsv: {}
json: {}
regexp: {}
